name: e ola
favicon: null
layout_spectrum: 0
typography_spectrum: 0.72816
title: >-
  we support humans to have fun, health and sustainability at the beat of their
  hearts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151314'
    - '#b9b2ac'
    - '#436d97'
    - '#ad7b34'
    - '#c21a22'
  brandStrength: 0.9877201337367296
  lightness: 0.6673706276342273
  saturation: 0.7436528075486422
  rhythmicContrast: 0.2353537541348487
purpose: []
