name: e ola
favicon: null
layout_spectrum: 0.8207341900561005
typography_spectrum: 0.9066170586738735
title: e ola
description: raising ideas for humanity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83215823-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
  brandStrength: 0.516071391524747
  lightness: 0.9465421892236918
  saturation: 0.13563029537908733
  rhythmicContrast: 0.4911202802322805
purpose: []
